name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: "opensuse/tumbleweed"


    steps:
      - run: zypper -n install git
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "${{ github.ref }}" "${{ github.head_ref }}" "${{ github.base_ref }}"
      - name: Clone output repository
        run: git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/marxin/test-output.git
      - name: Setup git config
        run: |
          git config --global user.email mliska@suse.cz
          git config --global user.name marxin
      - name: Change directory
        run: cd test-output
      - name: Change branch
        run: git checkout -b ${{ github.head_ref }}
        if: ${{ github.ref != 'refs/heads/main' }}
      - name: Modify repo
        run: |
          echo ${{ github.sha }} >> revision
          git add revision
          git commit -a -m 'Update'
          git push
